In [1]:
!pip install pandasql

from pandasql import sqldf
import pandas as pd

df = pd.read_csv('zepto_data.csv', encoding='latin1')

pysqldf = lambda q: sqldf(q, globals())

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.49)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2026.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26773 sha256=634e3f63c8ff6f33b8707b498ee9760cc97dc712e4b4a18806ddbb978aadd0a0
  Stored in directory: /root/.cache/pip/wheels/15/a1/e7/6f92f295b5272ae5c02365e6b8fa19cb93f16a537090a1cf27
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [2]:
!pip install  pandasql

from pandasql import sqldf
import pandas as pd

Requirement already satisfied: pandasql in /usr/local/lib/python3.12/dist-packages (0.7.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from pandasql) (2.0.49)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pandasql) (2026.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->pandasql) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)

In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

In [4]:
# Create tables
cursor.executescript('''
CREATE TABLE departments (
    dept_id INTEGER PRIMARY KEY,
    dept_name TEXT,
    location TEXT,
    budget REAL
);

CREATE TABLE employees (
    emp_id INTEGER PRIMARY KEY,
    emp_name TEXT,
    age INTEGER,
    gender TEXT,
    dept_id INTEGER,
    salary REAL,
    join_date TEXT,
    performance_score INTEGER,
    email TEXT,
    FOREIGN KEY (dept_id) REFERENCES departments(dept_id)
);
''')

# Insert departments (20 rows)
departments = [
    (1, 'Data Science', 'Bangalore', 5000000),
    (2, 'Engineering', 'Mumbai', 8000000),
    (3, 'Marketing', 'Delhi', 3000000),
    (4, 'Finance', 'Chennai', 4000000),
    (5, 'HR', 'Hyderabad', 2000000),
    (6, 'Sales', 'Pune', 3500000),
    (7, 'Operations', 'Kolkata', 4500000),
    (8, 'Product', 'Bangalore', 6000000),
    (9, 'Legal', 'Mumbai', 2500000),
    (10, 'IT Support', 'Delhi', 2000000),
    (11, 'Research', 'Bangalore', 7000000),
    (12, 'Customer Success', 'Chennai', 3000000),
    (13, 'Design', 'Pune', 2800000),
    (14, 'DevOps', 'Hyderabad', 5500000),
    (15, 'Analytics', 'Bangalore', 6500000),
    (16, 'Procurement', 'Mumbai', 3200000),
    (17, 'Admin', 'Delhi', 1800000),
    (18, 'QA', 'Chennai', 4000000),
    (19, 'Business Dev', 'Pune', 4200000),
    (20, 'Consulting', 'Kolkata', 5000000),
]
cursor.executemany('INSERT INTO departments VALUES (?,?,?,?)', departments)

# Insert employees (100 rows)
employees = [
    (1,'Aarav Shah',28,'M',1,75000,'2021-03-15',85,'aarav@company.com'),
    (2,'Priya Nair',32,'F',2,90000,'2019-07-01',90,'priya@company.com'),
    (3,'Rohan Mehta',25,'M',3,50000,'2022-01-10',70,'rohan@company.com'),
    (4,'Sneha Rao',29,'F',4,80000,'2020-05-20',88,'sneha@company.com'),
    (5,'Karan Patel',35,'M',5,60000,'2018-11-30',75,'karan@company.com'),
    (6,'Divya Iyer',27,'F',6,55000,'2022-06-15',72,'divya@company.com'),
    (7,'Arjun Sharma',31,'M',7,70000,'2020-09-01',80,'arjun@company.com'),
    (8,'Meera Joshi',26,'F',8,85000,'2021-12-01',92,'meera@company.com'),
    (9,'Rahul Gupta',33,'M',9,65000,'2019-03-22',78,'rahul@company.com'),
    (10,'Anjali Singh',28,'F',10,52000,'2022-08-10',68,'anjali@company.com'),
    (11,'Vikram Nair',30,'M',11,95000,'2020-02-14',94,'vikram@company.com'),
    (12,'Pooja Reddy',24,'F',12,48000,'2023-01-05',65,'pooja@company.com'),
    (13,'Aditya Kumar',29,'M',13,62000,'2021-07-19',77,'aditya@company.com'),
    (14,'Riya Desai',27,'F',14,88000,'2021-04-30',89,'riya@company.com'),
    (15,'Suresh Pillai',36,'M',15,92000,'2018-06-25',91,'suresh@company.com'),
    (16,'Nisha Verma',25,'F',1,72000,'2022-11-11',83,'nisha@company.com'),
    (17,'Manish Tiwari',34,'M',2,87000,'2019-09-09',86,'manish@company.com'),
    (18,'Kavya Menon',28,'F',3,53000,'2022-03-21',71,'kavya@company.com'),
    (19,'Siddharth Jain',31,'M',4,82000,'2020-07-07',87,'siddharth@company.com'),
    (20,'Ananya Bose',26,'F',5,58000,'2022-05-16',74,'ananya@company.com'),
    (21,'Nikhil Rao',29,'M',6,57000,'2021-10-10',73,'nikhil@company.com'),
    (22,'Shreya Agarwal',32,'F',7,73000,'2020-01-28',81,'shreya@company.com'),
    (23,'Rajesh Iyer',38,'M',8,89000,'2017-08-15',93,'rajesh@company.com'),
    (24,'Deepika Nair',27,'F',9,63000,'2021-06-06',76,'deepika@company.com'),
    (25,'Amit Sharma',33,'M',10,54000,'2019-12-12',69,'amit@company.com'),
    (26,'Priyanka Patel',28,'F',11,96000,'2021-02-28',95,'priyanka@company.com'),
    (27,'Varun Mehta',30,'M',12,49000,'2022-09-09',66,'varun@company.com'),
    (28,'Lakshmi Reddy',35,'F',13,64000,'2018-04-04',79,'lakshmi@company.com'),
    (29,'Rohit Gupta',27,'M',14,91000,'2021-11-11',90,'rohit@company.com'),
    (30,'Swati Joshi',29,'F',15,94000,'2020-08-08',93,'swati@company.com'),
    (31,'Gaurav Singh',31,'M',16,67000,'2020-10-10',80,'gaurav@company.com'),
    (32,'Harini Kumar',26,'F',17,45000,'2023-02-14',63,'harini@company.com'),
    (33,'Pranav Desai',28,'M',18,76000,'2021-05-05',84,'pranav@company.com'),
    (34,'Kritika Pillai',30,'F',19,83000,'2020-03-03',88,'kritika@company.com'),
    (35,'Sandeep Verma',37,'M',20,98000,'2017-07-07',96,'sandeep@company.com'),
    (36,'Tanvi Tiwari',25,'F',1,71000,'2022-12-12',82,'tanvi@company.com'),
    (37,'Vivek Menon',32,'M',2,88000,'2019-06-06',87,'vivek@company.com'),
    (38,'Rashmi Jain',27,'F',3,51000,'2022-04-04',70,'rashmi@company.com'),
    (39,'Akash Bose',30,'M',4,84000,'2020-06-06',89,'akash@company.com'),
    (40,'Padma Rao',28,'F',5,59000,'2022-07-07',75,'padma@company.com'),
    (41,'Chirag Iyer',29,'M',6,56000,'2021-09-09',72,'chirag@company.com'),
    (42,'Smita Agarwal',33,'F',7,74000,'2019-11-11',82,'smita@company.com'),
    (43,'Tarun Sharma',36,'M',8,90000,'2018-02-02',92,'tarun@company.com'),
    (44,'Vandana Nair',26,'F',9,61000,'2022-10-10',76,'vandana@company.com'),
    (45,'Manoj Patel',34,'M',10,55000,'2019-01-01',70,'manoj@company.com'),
    (46,'Ishita Mehta',27,'F',11,97000,'2021-08-08',95,'ishita@company.com'),
    (47,'Deepak Reddy',31,'M',12,50000,'2020-11-11',67,'deepak@company.com'),
    (48,'Nandita Gupta',28,'F',13,65000,'2021-03-03',79,'nandita@company.com'),
    (49,'Saurabh Joshi',29,'M',14,93000,'2021-01-01',91,'saurabh@company.com'),
    (50,'Radha Singh',32,'F',15,95000,'2019-05-05',94,'radha@company.com'),
    (51,'Abhishek Kumar',28,'M',1,73000,'2021-04-04',84,'abhishek@company.com'),
    (52,'Chandni Desai',26,'F',2,86000,'2022-02-02',88,'chandni@company.com'),
    (53,'Naveen Pillai',33,'M',3,52000,'2019-08-08',71,'naveen@company.com'),
    (54,'Geeta Verma',29,'F',4,81000,'2020-04-04',87,'geeta@company.com'),
    (55,'Hemant Tiwari',35,'M',5,61000,'2018-10-10',76,'hemant@company.com'),
    (56,'Jyoti Menon',27,'F',6,54000,'2022-01-01',72,'jyoti@company.com'),
    (57,'Kunal Jain',30,'M',7,72000,'2020-12-12',81,'kunal@company.com'),
    (58,'Lata Bose',34,'F',8,88000,'2018-09-09',92,'lata@company.com'),
    (59,'Mohit Rao',28,'M',9,64000,'2021-07-07',77,'mohit@company.com'),
    (60,'Neha Iyer',25,'F',10,53000,'2023-03-03',68,'neha@company.com'),
    (61,'Om Agarwal',31,'M',11,98000,'2020-05-05',96,'om@company.com'),
    (62,'Parvati Sharma',27,'F',12,47000,'2022-06-06',64,'parvati@company.com'),
    (63,'Qazi Nair',29,'M',13,63000,'2021-08-08',78,'qazi@company.com'),
    (64,'Renu Patel',32,'F',14,89000,'2019-10-10',90,'renu@company.com'),
    (65,'Sumit Mehta',36,'M',15,93000,'2018-03-03',93,'sumit@company.com'),
    (66,'Tara Reddy',26,'F',16,66000,'2022-08-08',80,'tara@company.com'),
    (67,'Uday Gupta',30,'M',17,46000,'2021-02-02',64,'uday@company.com'),
    (68,'Uma Joshi',28,'F',18,77000,'2021-06-06',85,'uma@company.com'),
    (69,'Vimal Singh',33,'M',19,85000,'2019-04-04',89,'vimal@company.com'),
    (70,'Wini Kumar',27,'F',20,99000,'2022-03-03',97,'wini@company.com'),
    (71,'Xavier Desai',29,'M',1,74000,'2021-05-05',84,'xavier@company.com'),
    (72,'Yash Pillai',31,'F',2,87000,'2020-07-07',88,'yash@company.com'),
    (73,'Zara Verma',25,'F',3,51000,'2023-01-01',70,'zara@company.com'),
    (74,'Ankit Tiwari',34,'M',4,83000,'2019-02-02',88,'ankit@company.com'),
    (75,'Bhavna Menon',28,'F',5,60000,'2022-04-04',75,'bhavna@company.com'),
    (76,'Chetan Jain',30,'M',6,57000,'2021-11-11',73,'chetan@company.com'),
    (77,'Disha Bose',26,'F',7,71000,'2022-09-09',81,'disha@company.com'),
    (78,'Eshan Rao',32,'M',8,91000,'2020-01-01',92,'eshan@company.com'),
    (79,'Falak Iyer',27,'F',9,62000,'2021-10-10',76,'falak@company.com'),
    (80,'Girish Agarwal',35,'M',10,56000,'2018-07-07',71,'girish@company.com'),
    (81,'Hema Sharma',29,'F',11,96000,'2020-09-09',95,'hema@company.com'),
    (82,'Ishan Nair',28,'M',12,48000,'2022-11-11',65,'ishan@company.com'),
    (83,'Jasmine Patel',31,'F',13,66000,'2020-08-08',80,'jasmine@company.com'),
    (84,'Kiran Mehta',33,'M',14,92000,'2019-07-07',91,'kiran@company.com'),
    (85,'Leela Reddy',27,'F',15,94000,'2021-12-12',93,'leela@company.com'),
    (86,'Madan Gupta',36,'M',16,68000,'2018-05-05',81,'madan@company.com'),
    (87,'Nalini Joshi',25,'F',17,44000,'2023-04-04',62,'nalini@company.com'),
    (88,'Omkar Singh',30,'M',18,78000,'2021-03-03',85,'omkar@company.com'),
    (89,'Pallavi Kumar',28,'F',19,84000,'2021-09-09',88,'pallavi@company.com'),
    (90,'Qureshi Desai',32,'M',20,100000,'2019-06-06',97,'qureshi@company.com'),
    (91,'Reema Pillai',27,'F',1,75000,'2022-07-07',83,'reema@company.com'),
    (92,'Sanjay Verma',34,'M',2,89000,'2019-03-03',87,'sanjay@company.com'),
    (93,'Tina Tiwari',26,'F',3,52000,'2022-05-05',71,'tina@company.com'),
    (94,'Usha Menon',31,'M',4,82000,'2020-10-10',87,'usha@company.com'),
    (95,'Vishal Jain',29,'M',5,59000,'2021-01-01',74,'vishal@company.com'),
    (96,'Winnie Bose',28,'F',6,55000,'2022-02-02',72,'winnie@company.com'),
    (97,'Xena Rao',33,'F',7,73000,'2020-03-03',82,'xena@company.com'),
    (98,'Yogesh Iyer',37,'M',8,92000,'2018-01-01',93,'yogesh@company.com'),
    (99,'Zoya Agarwal',26,'F',9,63000,'2022-10-10',77,'zoya@company.com'),
    (100,'Aryan Sharma',30,'M',10,54000,'2021-08-08',69,'aryan@company.com'),
]
cursor.executemany('INSERT INTO employees VALUES (?,?,?,?,?,?,?,?,?)', employees)
conn.commit()
print("✅ Tables created and data inserted successfully!")

# Helper function to run queries easily
def run_query(query):
    return pd.read_sql_query(query, conn)

✅ Tables created and data inserted successfully!

In [5]:
run_query("select * from employees limit 5")

,emp_id,emp_name,age,gender,dept_id,salary,join_date,performance_score,email
0,1,Aarav Shah,28,M,1,75000.0,2021-03-15,85,aarav@company.com
1,2,Priya Nair,32,F,2,90000.0,2019-07-01,90,priya@company.com
2,3,Rohan Mehta,25,M,3,50000.0,2022-01-10,70,rohan@company.com
3,4,Sneha Rao,29,F,4,80000.0,2020-05-20,88,sneha@company.com
4,5,Karan Patel,35,M,5,60000.0,2018-11-30,75,karan@company.com

In [6]:
run_query("select emp_id,emp_name,age,salary from employees limit 5")

   emp_id     emp_name  age   salary
0       1   Aarav Shah   28  75000.0
1       2   Priya Nair   32  90000.0
2       3  Rohan Mehta   25  50000.0
3       4    Sneha Rao   29  80000.0
4       5  Karan Patel   35  60000.0

In [7]:
run_query("select emp_name,emp_id from employees where salary>90000")

          emp_name  emp_id
0      Vikram Nair      11
1    Suresh Pillai      15
2   Priyanka Patel      26
3      Rohit Gupta      29
4      Swati Joshi      30
5    Sandeep Verma      35
6     Ishita Mehta      46
7    Saurabh Joshi      49
8      Radha Singh      50
9       Om Agarwal      61
10     Sumit Mehta      65
11      Wini Kumar      70
12       Eshan Rao      78
13     Hema Sharma      81
14     Kiran Mehta      84
15     Leela Reddy      85
16   Qureshi Desai      90
17     Yogesh Iyer      98

In [8]:
run_query("select emp_id,emp_name from employees where gender='F'")

    emp_id        emp_name
0        2      Priya Nair
1        4       Sneha Rao
2        6      Divya Iyer
3        8     Meera Joshi
4       10    Anjali Singh
5       12     Pooja Reddy
6       14      Riya Desai
7       16     Nisha Verma
8       18     Kavya Menon
9       20     Ananya Bose
10      22  Shreya Agarwal
11      24    Deepika Nair
12      26  Priyanka Patel
13      28   Lakshmi Reddy
14      30     Swati Joshi
15      32    Harini Kumar
16      34  Kritika Pillai
17      36    Tanvi Tiwari
18      38     Rashmi Jain
19      40       Padma Rao
20      42   Smita Agarwal
21      44    Vandana Nair
22      46    Ishita Mehta
23      48   Nandita Gupta
24      50     Radha Singh
25      52   Chandni Desai
26      54     Geeta Verma
27      56     Jyoti Menon
28      58       Lata Bose
29      60       Neha Iyer
30      62  Parvati Sharma
31      64      Renu Patel
32      66      Tara Reddy
33      68       Uma Joshi
34      70      Wini Kumar
35      72     Yash Pillai
36      73      Zara Verma
37      75    Bhavna Menon
38      77      Disha Bose
39      79      Falak Iyer
40      81     Hema Sharma
41      83   Jasmine Patel
42      85     Leela Reddy
43      87    Nalini Joshi
44      89   Pallavi Kumar
45      91    Reema Pillai
46      93     Tina Tiwari
47      96     Winnie Bose
48      97        Xena Rao
49      99    Zoya Agarwal

In [9]:
run_query("select emp_id,emp_name,salary from employees order by salary desc limit 10")

   emp_id        emp_name    salary
0      90   Qureshi Desai  100000.0
1      70      Wini Kumar   99000.0
2      35   Sandeep Verma   98000.0
3      61      Om Agarwal   98000.0
4      46    Ishita Mehta   97000.0
5      26  Priyanka Patel   96000.0
6      81     Hema Sharma   96000.0
7      11     Vikram Nair   95000.0
8      50     Radha Singh   95000.0
9      30     Swati Joshi   94000.0

In [10]:
run_query("select emp_name,age from employees order by age asc limit 5")

       emp_name  age
0   Pooja Reddy   24
1   Rohan Mehta   25
2   Nisha Verma   25
3  Tanvi Tiwari   25
4     Neha Iyer   25

In [11]:
run_query("select emp_name,gender,salary from employees where gender='F' and salary>80000")

          emp_name gender   salary
0       Priya Nair      F  90000.0
1      Meera Joshi      F  85000.0
2       Riya Desai      F  88000.0
3   Priyanka Patel      F  96000.0
4      Swati Joshi      F  94000.0
5   Kritika Pillai      F  83000.0
6     Ishita Mehta      F  97000.0
7      Radha Singh      F  95000.0
8    Chandni Desai      F  86000.0
9      Geeta Verma      F  81000.0
10       Lata Bose      F  88000.0
11      Renu Patel      F  89000.0
12      Wini Kumar      F  99000.0
13     Yash Pillai      F  87000.0
14     Hema Sharma      F  96000.0
15     Leela Reddy      F  94000.0
16   Pallavi Kumar      F  84000.0

In [12]:
run_query("select emp_name,dept_id from employees where dept_id=1 or dept_id=15")

          emp_name  dept_id
0       Aarav Shah        1
1    Suresh Pillai       15
2      Nisha Verma        1
3      Swati Joshi       15
4     Tanvi Tiwari        1
5      Radha Singh       15
6   Abhishek Kumar        1
7      Sumit Mehta       15
8     Xavier Desai        1
9      Leela Reddy       15
10    Reema Pillai        1

In [13]:
run_query("select emp_name, dept_id from employees where dept_id in (1,8,11,15)")

          emp_name  dept_id
0       Aarav Shah        1
1      Meera Joshi        8
2      Vikram Nair       11
3    Suresh Pillai       15
4      Nisha Verma        1
5      Rajesh Iyer        8
6   Priyanka Patel       11
7      Swati Joshi       15
8     Tanvi Tiwari        1
9     Tarun Sharma        8
10    Ishita Mehta       11
11     Radha Singh       15
12  Abhishek Kumar        1
13       Lata Bose        8
14      Om Agarwal       11
15     Sumit Mehta       15
16    Xavier Desai        1
17       Eshan Rao        8
18     Hema Sharma       11
19     Leela Reddy       15
20    Reema Pillai        1
21     Yogesh Iyer        8

In [14]:
run_query("select emp_name,salary from employees where salary between 60000 and 80000")

          emp_name   salary
0       Aarav Shah  75000.0
1        Sneha Rao  80000.0
2      Karan Patel  60000.0
3     Arjun Sharma  70000.0
4      Rahul Gupta  65000.0
5     Aditya Kumar  62000.0
6      Nisha Verma  72000.0
7   Shreya Agarwal  73000.0
8     Deepika Nair  63000.0
9    Lakshmi Reddy  64000.0
10    Gaurav Singh  67000.0
11    Pranav Desai  76000.0
12    Tanvi Tiwari  71000.0
13   Smita Agarwal  74000.0
14    Vandana Nair  61000.0
15   Nandita Gupta  65000.0
16  Abhishek Kumar  73000.0
17   Hemant Tiwari  61000.0
18      Kunal Jain  72000.0
19       Mohit Rao  64000.0
20       Qazi Nair  63000.0
21      Tara Reddy  66000.0
22       Uma Joshi  77000.0
23    Xavier Desai  74000.0
24    Bhavna Menon  60000.0
25      Disha Bose  71000.0
26      Falak Iyer  62000.0
27   Jasmine Patel  66000.0
28     Madan Gupta  68000.0
29     Omkar Singh  78000.0
30    Reema Pillai  75000.0
31        Xena Rao  73000.0
32    Zoya Agarwal  63000.0

In [15]:
run_query("select emp_name, join_date from employees where join_date between '2020-01-01' and '2021-12-31'")

          emp_name   join_date
0       Aarav Shah  2021-03-15
1        Sneha Rao  2020-05-20
2     Arjun Sharma  2020-09-01
3      Meera Joshi  2021-12-01
4      Vikram Nair  2020-02-14
5     Aditya Kumar  2021-07-19
6       Riya Desai  2021-04-30
7   Siddharth Jain  2020-07-07
8       Nikhil Rao  2021-10-10
9   Shreya Agarwal  2020-01-28
10    Deepika Nair  2021-06-06
11  Priyanka Patel  2021-02-28
12     Rohit Gupta  2021-11-11
13     Swati Joshi  2020-08-08
14    Gaurav Singh  2020-10-10
15    Pranav Desai  2021-05-05
16  Kritika Pillai  2020-03-03
17      Akash Bose  2020-06-06
18     Chirag Iyer  2021-09-09
19    Ishita Mehta  2021-08-08
20    Deepak Reddy  2020-11-11
21   Nandita Gupta  2021-03-03
22   Saurabh Joshi  2021-01-01
23  Abhishek Kumar  2021-04-04
24     Geeta Verma  2020-04-04
25      Kunal Jain  2020-12-12
26       Mohit Rao  2021-07-07
27      Om Agarwal  2020-05-05
28       Qazi Nair  2021-08-08
29      Uday Gupta  2021-02-02
30       Uma Joshi  2021-06-06
31    Xavier Desai  2021-05-05
32     Yash Pillai  2020-07-07
33     Chetan Jain  2021-11-11
34       Eshan Rao  2020-01-01
35      Falak Iyer  2021-10-10
36     Hema Sharma  2020-09-09
37   Jasmine Patel  2020-08-08
38     Leela Reddy  2021-12-12
39     Omkar Singh  2021-03-03
40   Pallavi Kumar  2021-09-09
41      Usha Menon  2020-10-10
42     Vishal Jain  2021-01-01
43        Xena Rao  2020-03-03
44    Aryan Sharma  2021-08-08

In [16]:
run_query("select emp_name from employees where emp_name like 'A%'")

         emp_name
0      Aarav Shah
1    Arjun Sharma
2    Anjali Singh
3    Aditya Kumar
4     Ananya Bose
5     Amit Sharma
6      Akash Bose
7  Abhishek Kumar
8    Ankit Tiwari
9    Aryan Sharma

In [17]:
run_query("select emp_name,email from employees where email like '%company%'")

        emp_name               email
0     Aarav Shah   aarav@company.com
1     Priya Nair   priya@company.com
2    Rohan Mehta   rohan@company.com
3      Sneha Rao   sneha@company.com
4    Karan Patel   karan@company.com
..           ...                 ...
95   Winnie Bose  winnie@company.com
96      Xena Rao    xena@company.com
97   Yogesh Iyer  yogesh@company.com
98  Zoya Agarwal    zoya@company.com
99  Aryan Sharma   aryan@company.com

[100 rows x 2 columns]

In [18]:
run_query("select emp_name,salary from employees where salary is null")

Empty DataFrame
Columns: [emp_name, salary]
Index: []

In [19]:
run_query("select emp_name,salary from employees where salary is not null limit 5")

      emp_name   salary
0   Aarav Shah  75000.0
1   Priya Nair  90000.0
2  Rohan Mehta  50000.0
3    Sneha Rao  80000.0
4  Karan Patel  60000.0

In [20]:
run_query("select count(*) as total_emp from employees")

   total_emp
0        100

In [21]:
run_query("select sum(salary) as total_salary from employees")

   total_salary
0     7210000.0

In [22]:
run_query("select max(salary) as highest_salary, min(salary) as lowest_salary, avg(salary) as average_salary  from employees")

   highest_salary  lowest_salary  average_salary
0        100000.0        44000.0         72100.0

In [23]:
run_query("select dept_id,round(avg(salary)) as avg_dept_salary from employees group by dept_id order by avg_dept_salary desc")

    dept_id  avg_dept_salary
0        20          99000.0
1        11          96400.0
2        15          93600.0
3        14          90600.0
4         8          89167.0
5         2          87833.0
6        19          84000.0
7         4          82000.0
8        18          77000.0
9         1          73333.0
10        7          72167.0
11       16          67000.0
12       13          64000.0
13        9          63000.0
14        5          59500.0
15        6          55667.0
16       10          54000.0
17        3          51500.0
18       12          48400.0
19       17          45000.0

In [24]:
run_query("select gender, count(emp_id) as gender_count from employees group by gender")

  gender  gender_count
0      F            50
1      M            50

In [25]:
run_query("select dept_id, avg(salary) as avg_salary from employees group by dept_id having avg_salary>80000")

   dept_id    avg_salary
0        2  87833.333333
1        4  82000.000000
2        8  89166.666667
3       11  96400.000000
4       14  90600.000000
5       15  93600.000000
6       19  84000.000000
7       20  99000.000000

In [26]:
run_query("select dept_id,count(emp_id) as num_of_emp from employees group by dept_id having num_of_emp>5")

   dept_id  num_of_emp
0        1           6
1        2           6
2        3           6
3        4           6
4        5           6
5        6           6
6        7           6
7        8           6
8        9           6
9       10           6

In [27]:
run_query("""
select e.emp_name,e.emp_id, d.dept_name,d.location
from employees e
inner join departments d
on e.dept_id=d.dept_id limit 10""")

       emp_name  emp_id     dept_name   location
0    Aarav Shah       1  Data Science  Bangalore
1    Priya Nair       2   Engineering     Mumbai
2   Rohan Mehta       3     Marketing      Delhi
3     Sneha Rao       4       Finance    Chennai
4   Karan Patel       5            HR  Hyderabad
5    Divya Iyer       6         Sales       Pune
6  Arjun Sharma       7    Operations    Kolkata
7   Meera Joshi       8       Product  Bangalore
8   Rahul Gupta       9         Legal     Mumbai
9  Anjali Singh      10    IT Support      Delhi

In [28]:
run_query("""
select e.emp_name,e.emp_id, d.dept_name,d.location
from employees e
left join departments d
on e.dept_id=d.dept_id limit 10""")

       emp_name  emp_id     dept_name   location
0    Aarav Shah       1  Data Science  Bangalore
1    Priya Nair       2   Engineering     Mumbai
2   Rohan Mehta       3     Marketing      Delhi
3     Sneha Rao       4       Finance    Chennai
4   Karan Patel       5            HR  Hyderabad
5    Divya Iyer       6         Sales       Pune
6  Arjun Sharma       7    Operations    Kolkata
7   Meera Joshi       8       Product  Bangalore
8   Rahul Gupta       9         Legal     Mumbai
9  Anjali Singh      10    IT Support      Delhi

In [29]:
run_query("""
select d.dept_name, count(e.emp_id) as headcount,d.budget
from departments d
left join employees e
on d.dept_id=e.dept_id
group by d.dept_name
order by headcount desc
""")

           dept_name  headcount     budget
0              Sales          6  3500000.0
1            Product          6  6000000.0
2         Operations          6  4500000.0
3          Marketing          6  3000000.0
4              Legal          6  2500000.0
5         IT Support          6  2000000.0
6                 HR          6  2000000.0
7            Finance          6  4000000.0
8        Engineering          6  8000000.0
9       Data Science          6  5000000.0
10          Research          5  7000000.0
11            DevOps          5  5500000.0
12            Design          5  2800000.0
13  Customer Success          5  3000000.0
14         Analytics          5  6500000.0
15                QA          3  4000000.0
16       Procurement          3  3200000.0
17        Consulting          3  5000000.0
18      Business Dev          3  4200000.0
19             Admin          3  1800000.0

In [30]:
run_query("""select emp_name,salary
from employees where  salary >
(select avg(salary) from employees)
order by salary desc""")

          emp_name    salary
0    Qureshi Desai  100000.0
1       Wini Kumar   99000.0
2    Sandeep Verma   98000.0
3       Om Agarwal   98000.0
4     Ishita Mehta   97000.0
5   Priyanka Patel   96000.0
6      Hema Sharma   96000.0
7      Vikram Nair   95000.0
8      Radha Singh   95000.0
9      Swati Joshi   94000.0
10     Leela Reddy   94000.0
11   Saurabh Joshi   93000.0
12     Sumit Mehta   93000.0
13   Suresh Pillai   92000.0
14     Kiran Mehta   92000.0
15     Yogesh Iyer   92000.0
16     Rohit Gupta   91000.0
17       Eshan Rao   91000.0
18      Priya Nair   90000.0
19    Tarun Sharma   90000.0
20     Rajesh Iyer   89000.0
21      Renu Patel   89000.0
22    Sanjay Verma   89000.0
23      Riya Desai   88000.0
24     Vivek Menon   88000.0
25       Lata Bose   88000.0
26   Manish Tiwari   87000.0
27     Yash Pillai   87000.0
28   Chandni Desai   86000.0
29     Meera Joshi   85000.0
30     Vimal Singh   85000.0
31      Akash Bose   84000.0
32   Pallavi Kumar   84000.0
33  Kritika Pillai   83000.0
34    Ankit Tiwari   83000.0
35  Siddharth Jain   82000.0
36      Usha Menon   82000.0
37     Geeta Verma   81000.0
38       Sneha Rao   80000.0
39     Omkar Singh   78000.0
40       Uma Joshi   77000.0
41    Pranav Desai   76000.0
42      Aarav Shah   75000.0
43    Reema Pillai   75000.0
44   Smita Agarwal   74000.0
45    Xavier Desai   74000.0
46  Shreya Agarwal   73000.0
47  Abhishek Kumar   73000.0
48        Xena Rao   73000.0

In [31]:
run_query("""
select emp_id,emp_name,dept_id,salary
from employees where salary in
(select max(salary) from employees
group by dept_id)
order by salary desc""")

    emp_id        emp_name  dept_id    salary
0       90   Qureshi Desai       20  100000.0
1       35   Sandeep Verma       20   98000.0
2       61      Om Agarwal       11   98000.0
3       11     Vikram Nair       11   95000.0
4       50     Radha Singh       15   95000.0
5       49   Saurabh Joshi       14   93000.0
6       65     Sumit Mehta       15   93000.0
7       15   Suresh Pillai       15   92000.0
8       84     Kiran Mehta       14   92000.0
9       98     Yogesh Iyer        8   92000.0
10       2      Priya Nair        2   90000.0
11      43    Tarun Sharma        8   90000.0
12       8     Meera Joshi        8   85000.0
13      69     Vimal Singh       19   85000.0
14      39      Akash Bose        4   84000.0
15      89   Pallavi Kumar       19   84000.0
16      88     Omkar Singh       18   78000.0
17       1      Aarav Shah        1   75000.0
18      91    Reema Pillai        1   75000.0
19      42   Smita Agarwal        7   74000.0
20      71    Xavier Desai        1   74000.0
21      86     Madan Gupta       16   68000.0
22      66      Tara Reddy       16   66000.0
23      83   Jasmine Patel       13   66000.0
24       9     Rahul Gupta        9   65000.0
25      48   Nandita Gupta       13   65000.0
26      44    Vandana Nair        9   61000.0
27      55   Hemant Tiwari        5   61000.0
28      21      Nikhil Rao        6   57000.0
29      76     Chetan Jain        6   57000.0
30      41     Chirag Iyer        6   56000.0
31      80  Girish Agarwal       10   56000.0
32      18     Kavya Menon        3   53000.0
33      60       Neha Iyer       10   53000.0
34       3     Rohan Mehta        3   50000.0
35      47    Deepak Reddy       12   50000.0
36      67      Uday Gupta       17   46000.0

In [32]:
run_query("""
select emp_name,salary,
rank() over (order by salary desc) as salary_rank
from employees
limit 10
""")

         emp_name    salary  salary_rank
0   Qureshi Desai  100000.0            1
1      Wini Kumar   99000.0            2
2   Sandeep Verma   98000.0            3
3      Om Agarwal   98000.0            3
4    Ishita Mehta   97000.0            5
5  Priyanka Patel   96000.0            6
6     Hema Sharma   96000.0            6
7     Vikram Nair   95000.0            8
8     Radha Singh   95000.0            8
9     Swati Joshi   94000.0           10

In [33]:
run_query("""
select emp_id,emp_name,gender,salary from employees group by salary
order by salary desc limit 10""")

   emp_id        emp_name gender    salary
0      90   Qureshi Desai      M  100000.0
1      70      Wini Kumar      F   99000.0
2      35   Sandeep Verma      M   98000.0
3      46    Ishita Mehta      F   97000.0
4      26  Priyanka Patel      F   96000.0
5      11     Vikram Nair      M   95000.0
6      30     Swati Joshi      F   94000.0
7      49   Saurabh Joshi      M   93000.0
8      15   Suresh Pillai      M   92000.0
9      29     Rohit Gupta      M   91000.0

In [34]:
run_query("""
select emp_name, emp_id, salary,gender,
rank() over (order by salary desc) as highest_salary_per_dept
from employees
group by dept_id
limit 10""")

         emp_name  emp_id   salary gender  highest_salary_per_dept
0   Sandeep Verma      35  98000.0      M                        1
1     Vikram Nair      11  95000.0      M                        2
2   Suresh Pillai      15  92000.0      M                        3
3      Priya Nair       2  90000.0      F                        4
4      Riya Desai      14  88000.0      F                        5
5     Meera Joshi       8  85000.0      F                        6
6  Kritika Pillai      34  83000.0      F                        7
7       Sneha Rao       4  80000.0      F                        8
8    Pranav Desai      33  76000.0      M                        9
9      Aarav Shah       1  75000.0      M                       10

In [35]:
run_query("""
select emp_name, dept_id,salary,
rank() over (partition by dept_id order by salary desc) as dept_rank
from employees
order by dept_id, dept_rank
limit 20
""")

          emp_name  dept_id   salary  dept_rank
0       Aarav Shah        1  75000.0          1
1     Reema Pillai        1  75000.0          1
2     Xavier Desai        1  74000.0          3
3   Abhishek Kumar        1  73000.0          4
4      Nisha Verma        1  72000.0          5
5     Tanvi Tiwari        1  71000.0          6
6       Priya Nair        2  90000.0          1
7     Sanjay Verma        2  89000.0          2
8      Vivek Menon        2  88000.0          3
9    Manish Tiwari        2  87000.0          4
10     Yash Pillai        2  87000.0          4
11   Chandni Desai        2  86000.0          6
12     Kavya Menon        3  53000.0          1
13   Naveen Pillai        3  52000.0          2
14     Tina Tiwari        3  52000.0          2
15     Rashmi Jain        3  51000.0          4
16      Zara Verma        3  51000.0          4
17     Rohan Mehta        3  50000.0          6
18      Akash Bose        4  84000.0          1
19    Ankit Tiwari        4  83000.0          2

In [36]:
run_query("""
SELECT emp_name, dept_id, salary,
RANK() OVER (PARTITION BY dept_id ORDER BY salary DESC) AS dept_rank
FROM employees
ORDER BY dept_id, dept_rank
LIMIT 20
""")

          emp_name  dept_id   salary  dept_rank
0       Aarav Shah        1  75000.0          1
1     Reema Pillai        1  75000.0          1
2     Xavier Desai        1  74000.0          3
3   Abhishek Kumar        1  73000.0          4
4      Nisha Verma        1  72000.0          5
5     Tanvi Tiwari        1  71000.0          6
6       Priya Nair        2  90000.0          1
7     Sanjay Verma        2  89000.0          2
8      Vivek Menon        2  88000.0          3
9    Manish Tiwari        2  87000.0          4
10     Yash Pillai        2  87000.0          4
11   Chandni Desai        2  86000.0          6
12     Kavya Menon        3  53000.0          1
13   Naveen Pillai        3  52000.0          2
14     Tina Tiwari        3  52000.0          2
15     Rashmi Jain        3  51000.0          4
16      Zara Verma        3  51000.0          4
17     Rohan Mehta        3  50000.0          6
18      Akash Bose        4  84000.0          1
19    Ankit Tiwari        4  83000.0          2

In [40]:
run_query ("""
    select emp_name,salary,
sum(salary) over (order by emp_id rows between unbounded preceding and current row ) as running_total
from employees
limit 10
""")

       emp_name   salary  running_total
0    Aarav Shah  75000.0        75000.0
1    Priya Nair  90000.0       165000.0
2   Rohan Mehta  50000.0       215000.0
3     Sneha Rao  80000.0       295000.0
4   Karan Patel  60000.0       355000.0
5    Divya Iyer  55000.0       410000.0
6  Arjun Sharma  70000.0       480000.0
7   Meera Joshi  85000.0       565000.0
8   Rahul Gupta  65000.0       630000.0
9  Anjali Singh  52000.0       682000.0